### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by runeflobakk** [unruly/java-8-matchers#13]
Plans for a 1.5 release anytime soon? 😃

**Comment by CliveEvans** [comment]
I would, but they didn't give me the keys to sign things when I left, for some strange reason ...

@jahed or @benjiman are probably our best hope ...

**Comment by jahed** [comment]
I've released 1.5. Maven Central should update in a few hours.

**Comment by CliveEvans** [comment]
Thanks mate.
